#!/bin/bash
read -p "License key (4 day free trial soon)  :  " response

if [ "$response" = "SPAC_TEST_1284" ]; then
    echo "Please wait until icllixMac Shaders is done. If you need get in contact at @sadosprey@gmail.com or @Chinhooks_DT on Roblox.com or @synthen_s on Discord."
else
 # echo "Command 'Shaders' cannot be executed. Please get a valid license key or get help @sadosprey@gmail.com or @Chinhooks_DT on Roblox.com or even @synthen_s on Discord."
echo "Incorrect license key or an error occured.
fi
